import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Footer from "../components/Shared/footer";
import NavBar from "../components/Shared/navBar";
import ReturnHello from "../components/Utils/returnHello";
import Login from "../pages/login";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [testLogin, setTestLogin] = useState(false);
  return (
    <>
      {/* <NavBar /> */}
      <div className={styles.container}>
        <Head>
          <title>Pharmaz | Home </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className="w-full flex bg-slate-300">
            <h1 className="mx-auto">Hello world | working</h1>
            <button className="mr-8 border border-gray-500 px-5 rounded-lg" onClick={() => setTestLogin(!testLogin)}>{testLogin ? `Logout` : `Login`}</button>
          </div>
          <NavBar></NavBar>
        </main>
      </div>
      {/* <Footer /> */}
    </>
  );
};

export default Home;
